# Generated by Django 4.1 on 2022-08-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0002_categorybyuser_product_owner_product_categoryforuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybyuser',
            options={'verbose_name': 'Category By User', 'verbose_name_plural': 'Categories By User'},
        ),
        migrations.AlterField(
            model_name='categorybyuser',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryForUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_api.categorybyuser', verbose_name='Category By Owner'),
        ),
    ]
