# Generated by Django 4.1 on 2022-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0003_alter_categorybyuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name'),
        ),
    ]
